### ISSUE TITLE
Nuget packages are configured wrong, Samples don't work,  ASP View/View Components Missing

### ISSUE THREAD

**Issue by weedkiller** [easyquery/AspNetCoreSamples#18]
I spend a lot of time on trying to get samples working or adding nugets, after reading documentation. I created a new 5,0 core project added easy query core nuget, but its installing & restoring with 4.7!!

- [ ] Where are the views and the js life cycle hooks?
- [ ] Where is the community version of JS, errors from JS code with deeper steps and complex data queries

I am using this[ Query Builder and its free](https://github.com/mistic100/jQuery-QueryBuilder) and [Kenj](http://knexjs.org/) easier to use and integrate into Core 5

Please make the samples and the learning curve easier, you have several products and indifferent places, please put everything in one place so its simple to make a decision and quick to get up and running. 

![image](https://user-images.githubusercontent.com/21086190/107131927-fb9b8580-68a8-11eb-98f9-5c71251d5708.png)

```

The latest nugets still have errors, please update docs page and make easy to install as angular components or view components.

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0618	'DatabaseErrorPageExtensions.UseDatabaseErrorPage(IApplicationBuilder)' is obsolete: 'This is obsolete and will be removed in a future version. Use DatabaseDeveloperPageExceptionFilter instead, see documentation at https://aka.ms/DatabaseDeveloperPageExceptionFilter.'	KorzhTest	C:\users\bjacobs\KorzhTest\KorzhTest\Startup.cs	44	Active
```

**Comment by korzh** [comment]
The error you posted is about Korzh.EasyQuery.Core package which is obsolete a long time ago. 
![image](https://user-images.githubusercontent.com/966694/107137837-f4ac5b80-6918-11eb-9668-10b1e2464379.png)

Here is [the latest demo for Angular](https://github.com/easyquery/AspNetCoreSamples/tree/ver-7.0/EqDemo.AspNetCoreAngular.AdvancedSearch)

And here is [the latest demo for Vue](https://github.com/easyquery/AspNetCoreSamples/tree/ver-7.0/EqDemo.AspNetCoreVue.AdvancedSearch)

They both are based on the latest build of version 7.0 that will be released in a week.
Could you please try any of them (or both) and [contact us](https://korzh.com/support) if anything goes wrong there.

**Comment by weedkiller** [comment]
Ok thanks, I will try again, I don't see any Views / View Component or Partials.
The Js file is also missing, I think its directly loading from some outside server. Can I add styles, icons etc.

How can I run a sample with code, I can try with some code, are there any other functions like distinct, group, aerage, sum etc.
