### ISSUE TITLE
 EasyQuery Result Format

### ISSUE THREAD

**Issue by mikheil09** [easyquery/AspNetCoreSamples#5]
Hello,

I need specific result for my reports. I can't find out how to get it using EasyQuery.

In my example I have three tables: "Person"(1 record), "Address"(2 records) and "Education"(3 records). When I do report using this three tables I get 6 records, so EasyQuery multiply records count, I know this is sql  "JOIN" standard behavior, but  I want to get just three records, because max records count in education is 3.

I made picture to describe this situation. Please take a look - 
![example](https://user-images.githubusercontent.com/2842079/41355640-09615482-6f33-11e8-9fa4-99027beded11.JPG)

Can you tell me if EasyQuery has this functionality?

**Comment by korzh** [comment]
You can only to get the whole result (6 records) and then render that result on the client the way you need.
